replicaCount: 1

image:
  repository: "kagameow/bbtest"
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /test
    port: 8080
readinessProbe:
  httpGet:
    path: /test
    port: 8080
